title:   Joy(Ruoqian) Wang
logo: "/images/meandjiujiu.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Joy, a data enthusiast stuffed with 6-year environmental academical knowledge. I am currently working in telecommunication engineering field and I also have some experience of customer service and management in hospitality industry.
  <br><br>
  I am passionate about diving in data, and building business logics from stakeholders' communications. And thanks to my multi-industries career path, I am able to understand and utilize data in business to deliver insights, most importantly, it made who I am today!
  <br><br>
  <a href="https://www.linkedin.com/in/joy-wang-387507a7/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/joy4396#!/?newProfile=&activeTab=0">View My Tableau Work Samples</a>
 
 
theme: jekyll-theme-minimal
